package gtna.routing;

import gtna.routing.node.identifier.Identifier;

/**
 * Interface for routes generated by routing algorithms that route using an
 * identifier space. Therefore, every routing attempt has a target identifier or
 * destination which the routing algorithms routes towards.
 * 
 * @author benni
 * 
 */
public interface IDRoute extends Route {
	/**
	 * Returns the target identifier or destination of this routing attempt.
	 * 
	 * @return target identifier of the routing attempt
	 */
	public Identifier dest();
}
